// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'entity/FavoriteList.dart';
import 'entity/FavoriteStation.dart';
import 'entity/RadioStation.dart';
import 'entity/RecentPlay.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7436822321649150065),
    name: 'RadioStation',
    lastPropertyId: const obx_int.IdUid(39, 224289506774434706),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7055442352269179791),
        name: 'changeuuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8528542704857721285),
        name: 'stationuuid',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 5620722255460710101),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7645634282218627524),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 211675961739616933),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5388273908987723261),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6758932614398533015),
        name: 'url_resolved',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8245103413055209371),
        name: 'homepage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2692280757466136166),
        name: 'favicon',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2506170921581120088),
        name: 'tags',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 7367851466417220482),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4195561971443945401),
        name: 'country',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 3304904983427098139),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2170736479540221164),
        name: 'countrycode',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 1253554855620850168),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7038970495037133022),
        name: 'state',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6231387693583788383),
        name: 'language',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(6, 3522972591340074282),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6914396567472035929),
        name: 'languagecodes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6797727692949477733),
        name: 'votes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 1544412373542852636),
        name: 'lastchangetime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 6801721406607847288),
        name: 'lastchangetime_iso8601',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 4604366046485410454),
        name: 'codec',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 5673508010651663359),
        name: 'bitrate',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 5372820193510985276),
        name: 'hls',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 8378882078187914987),
        name: 'lastcheckok',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 3737386988551192016),
        name: 'lastchecktime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 5210159892888898947),
        name: 'lastchecktime_iso8601',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 1702370152543036120),
        name: 'lastcheckoktime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 6299770043039354009),
        name: 'lastcheckoktime_iso8601',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 158186083144508268),
        name: 'lastlocalchecktime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 393528524449144912),
        name: 'lastlocalchecktime_iso8601',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 6480030708110486756),
        name: 'clicktimestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 1587718460057029785),
        name: 'clicktimestamp_iso8601',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 5437859335951710015),
        name: 'clickcount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 201768353899556053),
        name: 'clicktrend',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(31, 75124014264236609),
        name: 'ssl_error',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(32, 8448995127978754653),
        name: 'geo_lat',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(33, 4561516836486327785),
        name: 'geo_long',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(34, 7232268806701058316),
        name: 'has_extended_info',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(35, 7876709965945515235),
        name: 'started',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(36, 5774964569403398422),
        name: 'ID',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(37, 2062513243964066154),
        name: 'isActive',
        type: 1,
        flags: 8,
        indexId: const obx_int.IdUid(12, 5649675021521522315),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(38, 8292675629381617205),
        name: 'lastSeenFullSyncGeneration',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(13, 675024718858711640),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(39, 224289506774434706),
        name: 'syncStateInitialized',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2214360542772020583),
    name: 'FavoriteList',
    lastPropertyId: const obx_int.IdUid(5, 3363504792832135934),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8028293493521419087),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1459485673477153412),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(7, 5442191561095652699),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1905711520848489789),
        name: 'isDefault',
        type: 1,
        flags: 8,
        indexId: const obx_int.IdUid(8, 7069371790204048819),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1424440258622539855),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3363504792832135934),
        name: 'updatedAt',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1611906370417289392),
    name: 'FavoriteStation',
    lastPropertyId: const obx_int.IdUid(22, 3141465461916554209),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6452468973775345633),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1243634532110929198),
        name: 'listId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(9, 1205533648861828498),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2450231339943972769),
        name: 'stationuuid',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(10, 861384734453989807),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 7113638916684035402),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 4279314872788968489),
        name: 'updatedAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 3141465461916554209),
        name: 'stationId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(11, 1493285678863215958),
        relationField: 'station',
        relationTarget: 'RadioStation',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 7344015527001917086),
    name: 'RecentPlay',
    lastPropertyId: const obx_int.IdUid(4, 2872146127145242194),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4729350913541972653),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6498781372619669201),
        name: 'stationuuid',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(14, 935126559488356952),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4368189583747899021),
        name: 'playedAt',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(15, 478581687753755667),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2872146127145242194),
        name: 'stationId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(16, 143291213915090722),
        relationField: 'station',
        relationTarget: 'RadioStation',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 7344015527001917086),
    lastIndexId: const obx_int.IdUid(16, 143291213915090722),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      4077452207422917505,
      5935419198783768796,
      8280794123652600858,
      6054165979365884000,
      8729082814190750373,
      9123508400094236413,
      9048238777620518908,
      721762467889299945,
      6079243632105238459,
      7601727081102489417,
      5374139033089193640,
      1139687094527057731,
      3871618050026887941,
      5174967138384079818,
      7573191138188292295,
      2193726459788517408,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    RadioStation: obx_int.EntityDefinition<RadioStation>(
      model: _entities[0],
      toOneRelations: (RadioStation object) => [],
      toManyRelations: (RadioStation object) => {},
      getId: (RadioStation object) => object.ID,
      setId: (RadioStation object, int id) {
        object.ID = id;
      },
      objectToFB: (RadioStation object, fb.Builder fbb) {
        final changeuuidOffset = fbb.writeString(object.changeuuid);
        final stationuuidOffset = fbb.writeString(object.stationuuid);
        final nameOffset = fbb.writeString(object.name);
        final urlOffset = fbb.writeString(object.url);
        final url_resolvedOffset = fbb.writeString(object.url_resolved);
        final homepageOffset = fbb.writeString(object.homepage);
        final faviconOffset = fbb.writeString(object.favicon);
        final tagsOffset = fbb.writeString(object.tags);
        final countryOffset = fbb.writeString(object.country);
        final countrycodeOffset = fbb.writeString(object.countrycode);
        final stateOffset = fbb.writeString(object.state);
        final languageOffset = fbb.writeString(object.language);
        final languagecodesOffset = fbb.writeString(object.languagecodes);
        final codecOffset = fbb.writeString(object.codec);
        fbb.startTable(40);
        fbb.addOffset(0, changeuuidOffset);
        fbb.addOffset(1, stationuuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, urlOffset);
        fbb.addOffset(4, url_resolvedOffset);
        fbb.addOffset(5, homepageOffset);
        fbb.addOffset(6, faviconOffset);
        fbb.addOffset(7, tagsOffset);
        fbb.addOffset(8, countryOffset);
        fbb.addOffset(9, countrycodeOffset);
        fbb.addOffset(10, stateOffset);
        fbb.addOffset(11, languageOffset);
        fbb.addOffset(12, languagecodesOffset);
        fbb.addInt64(13, object.votes);
        fbb.addInt64(14, object.lastchangetime?.millisecondsSinceEpoch);
        fbb.addInt64(15, object.lastchangetime_iso8601?.millisecondsSinceEpoch);
        fbb.addOffset(16, codecOffset);
        fbb.addInt64(17, object.bitrate);
        fbb.addBool(18, object.hls);
        fbb.addBool(19, object.lastcheckok);
        fbb.addInt64(20, object.lastchecktime?.millisecondsSinceEpoch);
        fbb.addInt64(21, object.lastchecktime_iso8601?.millisecondsSinceEpoch);
        fbb.addInt64(22, object.lastcheckoktime?.millisecondsSinceEpoch);
        fbb.addInt64(
          23,
          object.lastcheckoktime_iso8601?.millisecondsSinceEpoch,
        );
        fbb.addInt64(24, object.lastlocalchecktime?.millisecondsSinceEpoch);
        fbb.addInt64(
          25,
          object.lastlocalchecktime_iso8601?.millisecondsSinceEpoch,
        );
        fbb.addInt64(26, object.clicktimestamp?.millisecondsSinceEpoch);
        fbb.addInt64(27, object.clicktimestamp_iso8601?.millisecondsSinceEpoch);
        fbb.addInt64(28, object.clickcount);
        fbb.addInt64(29, object.clicktrend);
        fbb.addInt64(30, object.ssl_error);
        fbb.addFloat64(31, object.geo_lat);
        fbb.addFloat64(32, object.geo_long);
        fbb.addBool(33, object.has_extended_info);
        fbb.addBool(34, object.started);
        fbb.addInt64(35, object.ID);
        fbb.addBool(36, object.isActive);
        fbb.addInt64(37, object.lastSeenFullSyncGeneration);
        fbb.addBool(38, object.syncStateInitialized);
        fbb.finish(fbb.endTable());
        return object.ID;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastchangetimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          32,
        );
        final lastchangetime_iso8601Value = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 34);
        final lastchecktimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          44,
        );
        final lastchecktime_iso8601Value = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 46);
        final lastcheckoktimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          48,
        );
        final lastcheckoktime_iso8601Value = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 50);
        final lastlocalchecktimeValue = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 52);
        final lastlocalchecktime_iso8601Value = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 54);
        final clicktimestampValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          56,
        );
        final clicktimestamp_iso8601Value = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 58);
        final object = RadioStation()
          ..changeuuid = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 4, '')
          ..stationuuid = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..url = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..url_resolved = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..homepage = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..favicon = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..tags = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 18, '')
          ..country = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 20, '')
          ..countrycode = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 22, '')
          ..state = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 24, '')
          ..language = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 26, '')
          ..languagecodes = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 28, '')
          ..votes = const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0)
          ..lastchangetime = lastchangetimeValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(lastchangetimeValue)
          ..lastchangetime_iso8601 = lastchangetime_iso8601Value == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(lastchangetime_iso8601Value)
          ..codec = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 36, '')
          ..bitrate = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            38,
            0,
          )
          ..hls = const fb.BoolReader().vTableGet(buffer, rootOffset, 40, false)
          ..lastcheckok = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            42,
            false,
          )
          ..lastchecktime = lastchecktimeValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(lastchecktimeValue)
          ..lastchecktime_iso8601 = lastchecktime_iso8601Value == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(lastchecktime_iso8601Value)
          ..lastcheckoktime = lastcheckoktimeValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(lastcheckoktimeValue)
          ..lastcheckoktime_iso8601 = lastcheckoktime_iso8601Value == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(
                  lastcheckoktime_iso8601Value,
                )
          ..lastlocalchecktime = lastlocalchecktimeValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(lastlocalchecktimeValue)
          ..lastlocalchecktime_iso8601 = lastlocalchecktime_iso8601Value == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(
                  lastlocalchecktime_iso8601Value,
                )
          ..clicktimestamp = clicktimestampValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(clicktimestampValue)
          ..clicktimestamp_iso8601 = clicktimestamp_iso8601Value == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(clicktimestamp_iso8601Value)
          ..clickcount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            60,
            0,
          )
          ..clicktrend = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            62,
            0,
          )
          ..ssl_error = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            64,
            0,
          )
          ..geo_lat = const fb.Float64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            66,
          )
          ..geo_long = const fb.Float64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            68,
          )
          ..has_extended_info = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            70,
            false,
          )
          ..started = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            72,
            false,
          )
          ..ID = const fb.Int64Reader().vTableGet(buffer, rootOffset, 74, 0)
          ..isActive = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            76,
            false,
          )
          ..lastSeenFullSyncGeneration = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            78,
            0,
          )
          ..syncStateInitialized = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            80,
            false,
          );

        return object;
      },
    ),
    FavoriteList: obx_int.EntityDefinition<FavoriteList>(
      model: _entities[1],
      toOneRelations: (FavoriteList object) => [],
      toManyRelations: (FavoriteList object) => {},
      getId: (FavoriteList object) => object.id,
      setId: (FavoriteList object, int id) {
        object.id = id;
      },
      objectToFB: (FavoriteList object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addBool(2, object.isDefault);
        fbb.addInt64(3, object.createdAt);
        fbb.addInt64(4, object.updatedAt);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final isDefaultParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final createdAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final updatedAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final object = FavoriteList(
          name: nameParam,
          isDefault: isDefaultParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    FavoriteStation: obx_int.EntityDefinition<FavoriteStation>(
      model: _entities[2],
      toOneRelations: (FavoriteStation object) => [object.station],
      toManyRelations: (FavoriteStation object) => {},
      getId: (FavoriteStation object) => object.id,
      setId: (FavoriteStation object, int id) {
        object.id = id;
      },
      objectToFB: (FavoriteStation object, fb.Builder fbb) {
        final stationuuidOffset = fbb.writeString(object.stationuuid);
        fbb.startTable(23);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.listId);
        fbb.addOffset(2, stationuuidOffset);
        fbb.addInt64(19, object.createdAt);
        fbb.addInt64(20, object.updatedAt);
        fbb.addInt64(21, object.station.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = FavoriteStation()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..listId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0)
          ..stationuuid = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..createdAt = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            42,
            0,
          )
          ..updatedAt = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            44,
            0,
          );
        object.station.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          46,
          0,
        );
        object.station.attach(store);
        return object;
      },
    ),
    RecentPlay: obx_int.EntityDefinition<RecentPlay>(
      model: _entities[3],
      toOneRelations: (RecentPlay object) => [object.station],
      toManyRelations: (RecentPlay object) => {},
      getId: (RecentPlay object) => object.id,
      setId: (RecentPlay object, int id) {
        object.id = id;
      },
      objectToFB: (RecentPlay object, fb.Builder fbb) {
        final stationuuidOffset = fbb.writeString(object.stationuuid);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, stationuuidOffset);
        fbb.addInt64(2, object.playedAt);
        fbb.addInt64(3, object.station.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = RecentPlay()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..stationuuid = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..playedAt = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          );
        object.station.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.station.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [RadioStation] entity fields to define ObjectBox queries.
class RadioStation_ {
  /// See [RadioStation.changeuuid].
  static final changeuuid = obx.QueryStringProperty<RadioStation>(
    _entities[0].properties[0],
  );

  /// See [RadioStation.stationuuid].
  static final stationuuid = obx.QueryStringProperty<RadioStation>(
    _entities[0].properties[1],
  );

  /// See [RadioStation.name].
  static final name = obx.QueryStringProperty<RadioStation>(
    _entities[0].properties[2],
  );

  /// See [RadioStation.url].
  static final url = obx.QueryStringProperty<RadioStation>(
    _entities[0].properties[3],
  );

  /// See [RadioStation.url_resolved].
  static final url_resolved = obx.QueryStringProperty<RadioStation>(
    _entities[0].properties[4],
  );

  /// See [RadioStation.homepage].
  static final homepage = obx.QueryStringProperty<RadioStation>(
    _entities[0].properties[5],
  );

  /// See [RadioStation.favicon].
  static final favicon = obx.QueryStringProperty<RadioStation>(
    _entities[0].properties[6],
  );

  /// See [RadioStation.tags].
  static final tags = obx.QueryStringProperty<RadioStation>(
    _entities[0].properties[7],
  );

  /// See [RadioStation.country].
  static final country = obx.QueryStringProperty<RadioStation>(
    _entities[0].properties[8],
  );

  /// See [RadioStation.countrycode].
  static final countrycode = obx.QueryStringProperty<RadioStation>(
    _entities[0].properties[9],
  );

  /// See [RadioStation.state].
  static final state = obx.QueryStringProperty<RadioStation>(
    _entities[0].properties[10],
  );

  /// See [RadioStation.language].
  static final language = obx.QueryStringProperty<RadioStation>(
    _entities[0].properties[11],
  );

  /// See [RadioStation.languagecodes].
  static final languagecodes = obx.QueryStringProperty<RadioStation>(
    _entities[0].properties[12],
  );

  /// See [RadioStation.votes].
  static final votes = obx.QueryIntegerProperty<RadioStation>(
    _entities[0].properties[13],
  );

  /// See [RadioStation.lastchangetime].
  static final lastchangetime = obx.QueryDateProperty<RadioStation>(
    _entities[0].properties[14],
  );

  /// See [RadioStation.lastchangetime_iso8601].
  static final lastchangetime_iso8601 = obx.QueryDateProperty<RadioStation>(
    _entities[0].properties[15],
  );

  /// See [RadioStation.codec].
  static final codec = obx.QueryStringProperty<RadioStation>(
    _entities[0].properties[16],
  );

  /// See [RadioStation.bitrate].
  static final bitrate = obx.QueryIntegerProperty<RadioStation>(
    _entities[0].properties[17],
  );

  /// See [RadioStation.hls].
  static final hls = obx.QueryBooleanProperty<RadioStation>(
    _entities[0].properties[18],
  );

  /// See [RadioStation.lastcheckok].
  static final lastcheckok = obx.QueryBooleanProperty<RadioStation>(
    _entities[0].properties[19],
  );

  /// See [RadioStation.lastchecktime].
  static final lastchecktime = obx.QueryDateProperty<RadioStation>(
    _entities[0].properties[20],
  );

  /// See [RadioStation.lastchecktime_iso8601].
  static final lastchecktime_iso8601 = obx.QueryDateProperty<RadioStation>(
    _entities[0].properties[21],
  );

  /// See [RadioStation.lastcheckoktime].
  static final lastcheckoktime = obx.QueryDateProperty<RadioStation>(
    _entities[0].properties[22],
  );

  /// See [RadioStation.lastcheckoktime_iso8601].
  static final lastcheckoktime_iso8601 = obx.QueryDateProperty<RadioStation>(
    _entities[0].properties[23],
  );

  /// See [RadioStation.lastlocalchecktime].
  static final lastlocalchecktime = obx.QueryDateProperty<RadioStation>(
    _entities[0].properties[24],
  );

  /// See [RadioStation.lastlocalchecktime_iso8601].
  static final lastlocalchecktime_iso8601 = obx.QueryDateProperty<RadioStation>(
    _entities[0].properties[25],
  );

  /// See [RadioStation.clicktimestamp].
  static final clicktimestamp = obx.QueryDateProperty<RadioStation>(
    _entities[0].properties[26],
  );

  /// See [RadioStation.clicktimestamp_iso8601].
  static final clicktimestamp_iso8601 = obx.QueryDateProperty<RadioStation>(
    _entities[0].properties[27],
  );

  /// See [RadioStation.clickcount].
  static final clickcount = obx.QueryIntegerProperty<RadioStation>(
    _entities[0].properties[28],
  );

  /// See [RadioStation.clicktrend].
  static final clicktrend = obx.QueryIntegerProperty<RadioStation>(
    _entities[0].properties[29],
  );

  /// See [RadioStation.ssl_error].
  static final ssl_error = obx.QueryIntegerProperty<RadioStation>(
    _entities[0].properties[30],
  );

  /// See [RadioStation.geo_lat].
  static final geo_lat = obx.QueryDoubleProperty<RadioStation>(
    _entities[0].properties[31],
  );

  /// See [RadioStation.geo_long].
  static final geo_long = obx.QueryDoubleProperty<RadioStation>(
    _entities[0].properties[32],
  );

  /// See [RadioStation.has_extended_info].
  static final has_extended_info = obx.QueryBooleanProperty<RadioStation>(
    _entities[0].properties[33],
  );

  /// See [RadioStation.started].
  static final started = obx.QueryBooleanProperty<RadioStation>(
    _entities[0].properties[34],
  );

  /// See [RadioStation.ID].
  static final ID = obx.QueryIntegerProperty<RadioStation>(
    _entities[0].properties[35],
  );

  /// See [RadioStation.isActive].
  static final isActive = obx.QueryBooleanProperty<RadioStation>(
    _entities[0].properties[36],
  );

  /// See [RadioStation.lastSeenFullSyncGeneration].
  static final lastSeenFullSyncGeneration =
      obx.QueryIntegerProperty<RadioStation>(_entities[0].properties[37]);

  /// See [RadioStation.syncStateInitialized].
  static final syncStateInitialized = obx.QueryBooleanProperty<RadioStation>(
    _entities[0].properties[38],
  );
}

/// [FavoriteList] entity fields to define ObjectBox queries.
class FavoriteList_ {
  /// See [FavoriteList.id].
  static final id = obx.QueryIntegerProperty<FavoriteList>(
    _entities[1].properties[0],
  );

  /// See [FavoriteList.name].
  static final name = obx.QueryStringProperty<FavoriteList>(
    _entities[1].properties[1],
  );

  /// See [FavoriteList.isDefault].
  static final isDefault = obx.QueryBooleanProperty<FavoriteList>(
    _entities[1].properties[2],
  );

  /// See [FavoriteList.createdAt].
  static final createdAt = obx.QueryIntegerProperty<FavoriteList>(
    _entities[1].properties[3],
  );

  /// See [FavoriteList.updatedAt].
  static final updatedAt = obx.QueryIntegerProperty<FavoriteList>(
    _entities[1].properties[4],
  );
}

/// [FavoriteStation] entity fields to define ObjectBox queries.
class FavoriteStation_ {
  /// See [FavoriteStation.id].
  static final id = obx.QueryIntegerProperty<FavoriteStation>(
    _entities[2].properties[0],
  );

  /// See [FavoriteStation.listId].
  static final listId = obx.QueryIntegerProperty<FavoriteStation>(
    _entities[2].properties[1],
  );

  /// See [FavoriteStation.stationuuid].
  static final stationuuid = obx.QueryStringProperty<FavoriteStation>(
    _entities[2].properties[2],
  );

  /// See [FavoriteStation.createdAt].
  static final createdAt = obx.QueryIntegerProperty<FavoriteStation>(
    _entities[2].properties[3],
  );

  /// See [FavoriteStation.updatedAt].
  static final updatedAt = obx.QueryIntegerProperty<FavoriteStation>(
    _entities[2].properties[4],
  );

  /// See [FavoriteStation.station].
  static final station = obx.QueryRelationToOne<FavoriteStation, RadioStation>(
    _entities[2].properties[5],
  );
}

/// [RecentPlay] entity fields to define ObjectBox queries.
class RecentPlay_ {
  /// See [RecentPlay.id].
  static final id = obx.QueryIntegerProperty<RecentPlay>(
    _entities[3].properties[0],
  );

  /// See [RecentPlay.stationuuid].
  static final stationuuid = obx.QueryStringProperty<RecentPlay>(
    _entities[3].properties[1],
  );

  /// See [RecentPlay.playedAt].
  static final playedAt = obx.QueryIntegerProperty<RecentPlay>(
    _entities[3].properties[2],
  );

  /// See [RecentPlay.station].
  static final station = obx.QueryRelationToOne<RecentPlay, RadioStation>(
    _entities[3].properties[3],
  );
}
